spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/SC_dev
    username: postgres
    password: Sergeyiv1411
  flyway:
    baseline-on-migrate: true
